Add laba2
MTasia/Laboratory-work-Cpp pull request #5
Opened 2020-10-08 21:33 UTC by MTasia

2020-10-09 09:35 UTC, Gandy123 commented on Lab2.cpp
> +	glEnd();
уберите это в класс, тогда можно будет убрать Getp1 и getx

2020-10-09 09:36 UTC, Gandy123 commented on Lab2.cpp
> +	glEnd();
то же самое

2020-10-09 09:36 UTC, Gandy123 requested changes
done

2020-10-10 10:09 UTC, merged

2020-10-10 10:15 UTC, MTasia commented
убрала функции в классы